---
# This file is managed centrally by modulesync
#   https://github.com/theforeman/foreman-installer-modulesync
rvm:
  - 2.1.5
env:
  global:
    - PARALLEL_TEST_PROCESSORS=16
  matrix:
    # First test the major distros
    - PUPPET_VERSION=4.6 ONLY_OS=centos-6-x86_64,centos-7-x86_64,debian-7-x86_64,debian-8-x86_64,ubuntu-14-x86_64,ubuntu-14.04-x86_64,ubuntu-16-x86_64,ubuntu-16.04-x86_64
    # Test the rest of the supported platforms
    - PUPPET_VERSION=4.6 EXCLUDE_OS=centos-6-x86_64,centos-7-x86_64,debian-7-x86_64,debian-8-x86_64,ubuntu-14-x86_64,ubuntu-14.04-x86_64,ubuntu-16-x86_64,ubuntu-16.04-x86_64,scientific-6-x86_64,scientific-7-x86_64
matrix:
  fast_finish: true
  include:
    # Limit the OS set we test Ruby 2.2 with.
    - rvm: 2.2.6
      env: PUPPET_VERSION=4.6 ONLY_OS="debian-8-x86_64,centos-7-x86_64,ubuntu-16-x86_64,ubuntu-16.04-x86_64,freebsd-10-amd64,windows-2012 R2-x64"
    # Limit the OS set we test Ruby 2.3 with.
    - rvm: 2.3.0
      env: PUPPET_VERSION=4.6 ONLY_OS="debian-8-x86_64,centos-7-x86_64,ubuntu-16-x86_64,ubuntu-16.04-x86_64,freebsd-10-amd64,windows-2012 R2-x64"
    # Acceptance tests
    - rvm: 2.3.1
      dist: trusty
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/centos-7
      script: bundle exec rake beaker
      services: docker
      bundler_args: --without development
    - rvm: 2.3.1
      dist: trusty
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/debian-8
      script: bundle exec rake beaker
      services: docker
      bundler_args: --without development
bundler_args: --without system_tests development
sudo: false
