name: Nightly tests

on:
  schedule:
    - cron: '4 4 * * *'

jobs:
  unit:
    if: github.repository == 'theforeman/puppet-foreman'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "2.5"
          - "2.4"
        puppet:
          - "6"
          - "5"
        exclude:
          - ruby: "2.5"
            puppet: "5"
          - ruby: "2.4"
            puppet: "6"
    env:
      PUPPET_VERSION: "${{ matrix.puppet }}.0"
    name: Puppet ${{ matrix.puppet }} (Ruby ${{ matrix.ruby }})
    steps:
      - uses: actions/checkout@v2
      - name: Setup ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-${{ matrix.puppet }}-${{ matrix.ruby }}-gems-unit-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.puppet }}-${{ matrix.ruby }}-gems-unit-
      - name: Install dependencies
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle config without 'development system_tests'
          bundle install --jobs 4 --retry 3
      - name: Run tests
        run: bundle exec rake

  build_cache:
    if: github.repository == 'theforeman/puppet-foreman'
    runs-on: ubuntu-latest
    steps:
      - name: Enable IPv6 on docker
        run: |
          echo '{"ipv6":true,"fixed-cidr-v6":"2001:db8:1::/64"}' | sudo tee /etc/docker/daemon.json
          sudo service docker restart
      - uses: actions/checkout@v2
      - name: Setup ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.7"
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-2.7-gems-acceptance-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-2.7-gems-acceptance-
      - name: Install dependencies
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle config without 'development test'
          bundle install --jobs 4 --retry 3

  acceptance:
    if: github.repository == 'theforeman/puppet-foreman'
    needs: build_cache
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        setfile:
          - centos7-64{hostname=centos7-64.example.com}
          - centos8-64{hostname=centos8-64.example.com}
          - debian10-64{hostname=debian10-64.example.com}
          - ubuntu1804-64{hostname=ubuntu1804-64.example.com}
        puppet:
          - "6"
          - "5"
    name: Puppet ${{ matrix.puppet }} - ${{ matrix.setfile }}
    steps:
      - name: Enable IPv6 on docker
        run: |
          echo '{"ipv6":true,"fixed-cidr-v6":"2001:db8:1::/64"}' | sudo tee /etc/docker/daemon.json
          sudo service docker restart
      - uses: actions/checkout@v2
      - name: Setup ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.7"
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-2.7-gems-acceptance-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-2.7-gems-acceptance-
      - name: Install dependencies
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle config without 'development test'
          bundle install --jobs 4 --retry 3
      - name: Run tests
        run: bundle exec rake beaker
        env:
          BEAKER_PUPPET_COLLECTION: puppet${{ matrix.puppet }}
          BEAKER_setfile: ${{ matrix.setfile }}
